[project]
name = "majordome-build"
version = "0.1.0"
description = "Build system for Majordome's stack."
readme = "README.md"
authors = [
    { name = "Walter Dal'Maz Silva", email = "walter.dalmazsilva@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "docstring-parser>=0.18.0",
    "ipython>=9.14.0",
    "pygments>=2.20.0",
    "rich>=15.0.0",
]

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"

[project.scripts]
majordome-build = "majordome_build:main"
majordome-build-qmd = "majordome_build.compile_qmd:main"
